# Democracy Player - an RSS based video player application
# Copyright (C) 2005-2006 Participatory Culture Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  
USA

.TH DEMOCRACYPLAYER 1 "April 2, 2006"
.SH NAME
democracyplayer \- a GTK+ based RSS video aggregator
.SH SYNOPSIS
.B democracyplayer
.RB [ "\-\-help" ]
.RB [ "\-\-version" ]
.SH DESCRIPTION
.B "Democracy Player"
is a platform for Internet television and video. An intuitive interface
lets users subscribe to channels, watch video, and build a video library.
.SH OPTIONS
.B \-\-help
Show a help text and exit.
.PP
.B \-\-version
Show version information and exit.
.SH BUGS
Please report any bugs at https://develop.participatoryculture.org/projects/dtv/newticket
.SH LICENCE
.B democracyplayer
is covered by the GNU General Public License (GPL).
#.SH SEE ALSO
#.BR kitty (1).
.SH AUTHORS
Nick Nassar,
Geoff Schmidt,
Luc Heinrich,
Ben Dean-Kawamura,
Nick Reville,
Matt Bret, and
Chris Lahey.
.PP
This manual page was written by Uwe Hermann <uwe@hermann-uwe.de>,
for the Debian GNU/Linux system (but may be used by others).
.SH THANKS
Holmes Wilson,
Tiffiny Cheng,
Colin Mitchell,
David Moore,
Buzz,
Morgan Knutson,
Padgett Arango,
Webneo (Design Contest winner!),
Dean Jansen,
Michael Bell-smith,
Samuel Felder,
Andy Ross,
Matt Griffin,
Adam Conover,
Tom Woodhams (icon design),
Neil Cook,
Dan Funderburg (T-shirts), and
Tekriti Software (channel guide).
