.TH MIRO 1 "February 11, 2009"
.SH NAME
miro \- a GTK+ based RSS video aggregator and player
.SH SYNOPSIS
.B miro
.RB [ OPTIONS ]
.SH DESCRIPTION
.B "Miro"
is a platform for Internet television and video.  An intuitive interface
lets users subscribe to podcasts, watch video, and build a video library.
.SH OPTIONS
Please read
.B "miro \-\-help"
for a list of all available Miro command line options.
.SH HELP
Forums and other help are available at http://getmiro.com/ .
.SH BUGS
Please report any bugs at http://bugzilla.pculture.org/ .
.SH LICENCE
.B Miro
is covered by the GNU General Public License (GPL), either version 2 of
the license, or (at your option) any later version.
.SH AUTHORS
Nick Nassar,
Geoff Schmidt,
Luc Heinrich,
Ben Dean-Kawamura,
Nick Reville,
Matt Bret, 
Chris Lahey,
Will Kahn-Greene,
Paul Swartz, and
Chris Webber.
.PP
This manual page was originally written by Uwe Hermann <uwe@hermann-uwe.de>,
for the Debian GNU/Linux system (but may be used by others).  It was updated
by others.
.SH THANKS
Holmes Wilson,
Tiffiny Cheng,
Colin Mitchell,
David Moore,
Buzz,
Morgan Knutson,
Padgett Arango,
Webneo (Design Contest winner!),
Dean Jansen,
Michael Bell-smith,
Samuel Felder,
Andy Ross,
Matt Griffin,
Adam Conover,
Tom Woodhams (icon design),
Neil Cook,
Dan Funderburg (T-shirts), and
Tekriti Software (channel guide).
