#!/bin/bash

# usage: maketarball
#        maketarball <version>
#        maketarball --dir <dir> <version>
#
# With no arguments, this creates a source tarball from the trunk with a
# filename based on the date.
#
# If you pass in the svn-dir argument, then this will create a tarball
# of that svn directory.
#
# To create a tarball of version 1.0, do:
#
#    ./maketarball 1.0
#
# To create a tarball of a specific directory in svn, do:
#
#    ./maketarball --dir tags/Miro-1.1 1.1
#
# or:
#
#    ./maketarball --dir branches/Miro-1.1 1.1

mkdir temp-miro
cd temp-miro
if [ "x-$1" == "x-" ]; then
    svn co https://svn.participatoryculture.org/svn/dtv/trunk/tv
    tag=`date +%Y%m%d`
else
    if [ "$1" == "--dir" ]; then
        svn co https://svn.participatoryculture.org/svn/dtv/$2/tv
        tag=$3
    else
        svn co https://svn.participatoryculture.org/svn/dtv/tags/Miro-$1/tv
        tag=$1
    fi
fi

cd tv

# go through app.config.template and expand the revision-related properties
cd resources
REVISION_NUM=`svn info | grep "^Revision:" | mawk '{ print($2) }'`
REVISION_URL=`svn info | grep "^URL:" | mawk '{ print($2) }'`
REVISION="$REVISION_URL - $REVISION_NUM"

# this looks awful, but it just replaces / with \/
REVISION_NUM_ESCAPED=`echo $REVISION_NUM | sed "s/\\\\//\\\\\\\\\\\\//g"`
REVISION_URL_ESCAPED=`echo $REVISION_URL | sed "s/\\\\//\\\\\\\\\\\\//g"`
REVISION_ESCAPED=`echo $REVISION         | sed "s/\\\\//\\\\\\\\\\\\//g"`

# echo "$REVISION_NUM $REVISION_NUM_ESCAPED"
# echo "$REVISION_URL $REVISION_URL_ESCAPED"
# echo "$REVISION $REVISION_ESCAPED"

cat < app.config.template | sed "s/^appRevisionNum .*$/appRevisionNum = $REVISION_NUM_ESCAPED/;s/^appRevisionURL .*$/appRevisionURL = $REVISION_URL_ESCAPED/;s/^appRevision .*$/appRevision = $REVISION_ESCAPED/" > app.config.template2
mv app.config.template2 app.config.template
cd ..
cd ..

mv tv Miro-$tag
tar zcvf Miro-$tag.tar.gz --exclude=.svn Miro-$tag
mv Miro-$tag.tar.gz ..
cd ..
rm -Rf temp-miro
