#!/bin/bash

#Make directory structure for easy upload
mkdir $2$3
#mkdir $2$3/src
mkdir $2$3/fc4

#Make tarball and copy it into directory
svn co https://svn.participatoryculture.org/svn/dtv/trunk/resources/
resources/tv/maketarball $2$3
#cp Democracy-$2$3.tar.gz $2$3/src/

#Get the spec
svn cat https://svn.participatoryculture.org/svn/dtv/tags/Democracy-Player-$2/resources/tv/fedora/Democracy.spec > Democracy.spec
cp Democracy-$2$3.tar.gz /usr/src/redhat/SOURCES 
cp Democracy.spec /usr/src/redhat/SPECS/Democracy.spec

#build the rpm
sudo rpmbuild --ba /usr/src/redhat/SPECS/Democracy.spec 

#Copy the RPMs into the directory
cp /usr/src/redhat/SRPMS/Democracy-$2-1.src.rpm $2$3/fc4/Democracy-$2-1.src.rpm
cp /usr/src/redhat/RPMS/i386/Democracy-$2-1.i386.rpm $2$3/fc4/Democracy-$2-1.i386.rpm
cp /usr/src/redhat/RPMS/i386/Democracy-debuginfo-$2-1.i386.rpm $2$3/fc4/Democracy-debuginfo-$2-1.i386.rpm 

#copy Directory onto PCF2 user's home directory
echo "Press enter to upload files..."
read i
scp -r $2$3 $1@pcf2.osuosl.org:.

#File Cleanup
echo "Cleaning up files..."
rm -rf Democracy-$2$3.tar.gz
rm -rf resources/
rm -f Democracy*
rm -rf /usr/src/redhat/SRPMS/Democracy-$2-1.src.rpm
rm -rf /usr/src/redhat/RPMS/i386/Democracy-$2-1.i386.rpm 
rm -rf /usr/src/redhat/RPMS/i386/Democracy-debuginfo-$2-1.i386.rpm 
