#!/bin/bash

# Syntax: ./fc7 <username> <tag>
# example: ./fc7 willg 0.9.9-rc0
# example: ./fc7 willg 0.9.9

#Make directory structure for easy upload
mkdir $2$3
mkdir $2$3/src
mkdir $2$3/fc6

#Make tarball and copy it into directory
svn co https://svn.participatoryculture.org/svn/dtv/trunk/resources/
resources/tv/maketarball $2$3
cp Miro-$2$3.tar.gz $2$3/src/

#Get the spec
svn cat https://svn.participatoryculture.org/svn/dtv/tags/Democracy-Player-$2/resources/tv/fedora/Miro.spec > Miro.spec
sudo cp Miro-$2$3.tar.gz /usr/src/redhat/SOURCES 
sudo cp Miro.spec /usr/src/redhat/SPECS 

#build the rpm
sudo rpmbuild --ba /usr/src/redhat/SPECS/Miro.spec 

#Copy the RPMs into the directory
cp /usr/src/redhat/SRPMS/Miro-$2-1.src.rpm $2$3/fc7/Miro-$2-1.src.rpm
cp /usr/src/redhat/RPMS/i386/Miro-$2-1.i386.rpm $2$3/fc7/Miro-$2-1.i386.rpm
cp /usr/src/redhat/RPMS/i386/Miro-debuginfo-$2-1.i386.rpm $2$3/fc7/Miro-debuginfo-$2-1.i386.rpm 

#copy Directory onto PCF2 user's home directory
echo "Press enter to upload files...  or ctrl-c"
read i

scp -r $2$3 $1@pculture.org:.

#File Cleanup
echo "Cleaning up files..."
rm -rf Miro-$2$3.tar.gz
rm -rf resources/
rm -f Miro*
sudo rm -rf /usr/src/redhat/SRPMS/Miro-$2-1.src.rpm
sudo rm -rf /usr/src/redhat/RPMS/i386/Miro-$2-1.i386.rpm
sudo rm -rf /usr/src/redhat/RPMS/i386/Miro-debuginfo-$2-1.i386.rpm 
