#!/bin/bash

mkdir demotemp
cd demotemp

#If no tag is specified...
if [ "x-$2" == "x-" ]; then
	svn co https://svn.participatoryculture.org/svn/dtv/trunk/tv
 	tag=`date +%Y-%m-%d`
else
	#Check out code and build
	svn co https://svn.participatoryculture.org/svn/dtv/tags/Democracy-Player-$2$3/tv
	tag=$2$3
fi
	cd tv/platform/osx/
	./build.sh -make-dmg

	#upload it if username was specified 
	if [ "x-$1" != "x-" ]; then
		if [ "x-$2" != "x-" ]; then
			date=`date +%Y-%m-%d`
			mv Democracy-$date.dmg Democracy-$tag.dmg
		fi 
		echo "Press enter to upload .dmg file..."
		read i
		scp Democracy-$tag.dmg $1@pcf2.osuosl.org:/data/pculture/nightlies/
	else
	#otherwise just copy it to the desktop
		cp Democracy-$tag.dmg /Users/$USER/Desktop/
	fi

	cd ..
	cd ..
	cd ..

cd ..

rm -rf demotemp
