#!/bin/bash

#If no tag is specified...
if [ "x-$2" == "x-" ]; then
	tag=`date +%Y-%m-%d`
	trunk=https://svn.participatoryculture.org/svn/dtv/trunk/
else
	#Check out code and build
	tag=$2$3
	trunk=https://svn.participatoryculture.org/svn/dtv/tags/Democracy-Player-$2$3/
fi
	mkdir Democracy-Player-$tag
	cd Democracy-Player-$tag

	#Check out code
	svn co $trunk/tv
	if [ $? != 0 ]; then
		echo "svn co $trunk/tv failed"
		exit 1
	fi
	svn co $trunk/dtv-binary-kit-mac 
	if [ $? != 0 ]; then
                echo "svn co $trunk/dtv-binary-kit-mac failed"
                exit 1
        fi

	cd tv/platform/osx/
	./build.sh -make-dmg
	if [ $? != 0 ]; then
                echo "./build.sh -make-dmg failed"
                exit 1
        fi


	#upload it if username was specified 
	if [ "x-$1" != "x-" ]; then
		if [ "x-$2" != "x-" ]; then
			date=`date +%Y-%m-%d`
			mv Democracy-$date.dmg Democracy-$tag.dmg
		fi 
		echo "Press enter to upload .dmg file..."
		read i
		scp Democracy-$tag.dmg $1@pcf2.osuosl.org:/data/pculture/nightlies/
	else
	#otherwise just copy it to the desktop
		cp Democracy-$tag.dmg /Users/$USER/Desktop/
	fi

	cd ..
	cd ..
	cd ..

cd ..

rm -rf Democracy-Player-$tag
