#!/bin/bash

#If no tag is specified...
if [ "x-$2" == "x-" ]; then
	tag=`date +%Y-%m-%d`
	trunk=https://svn.participatoryculture.org/svn/dtv/trunk/
else
	#Specify tag
	tag=$2$3
	trunk=https://svn.participatoryculture.org/svn/dtv/tags/Democracy-Player-$2$3/
fi
	mkdir Democracy-Player-$tag
	if [ $? != 0 ]; then
               update=1
	       echo "directory already exists, updating"
	else
		update=0
        fi

	cd Democracy-Player-$tag

	#Check out code
	if [ $update != 0 ]; then
                cd tv/
		svn up
		cd ../dtv-binary-kit-mac/
		svn up
		cd ..
	else 
		svn co $trunk/tv
	
	        if [ $? != 0 ]; then
                	echo "svn co $trunk/tv failed"
        	        exit 1
	        fi

	        svn co $trunk/dtv-binary-kit-mac

	        if [ $? != 0 ]; then
                	echo "svn co $trunk/dtv-binary-kit-mac failed"
        	        exit 1
	        fi

        fi

	cd tv/platform/osx/
	./build.sh -make-dmg
	if [ $? != 0 ]; then
                echo "./build.sh -make-dmg failed"
                exit 1
        fi


	#upload it if username was specified 
	if [ "x-$1" != "x-" ]; then
		if [ "x-$2" != "x-" ]; then
			date=`date +%Y-%m-%d`
			mv Democracy-$date.dmg Democracy-$tag.dmg
		fi 
		echo "Press enter to upload .dmg file..."
		read i
		scp Democracy-$tag.dmg $1@pcf2.osuosl.org:/data/pculture/nightlies/
	else
	#otherwise just copy it to the desktop
		cp Democracy-$tag.dmg /Users/$USER/Desktop/
	fi

exit 0
