#!/bin/bash

mkdir demotemp
cd demotemp

#Check out code and build
svn co https://svn.participatoryculture.org/svn/dtv/tags/Democracy-Player-$2$3/tv

cd tv/platform/osx/
./build.sh -make-dmg

#Rename it and upload it
mv Democracy-*dmg Democracy-$2$3-ppc.dmg
mkdir $2$3
mkdir $2$3/OSX
mv Democracy-$2$3-intel.dmg $2$3/OSX/

scp -r $2$3 $1@pcf2.osuosl.org:.

cd ..
cd ..
cd ..
cd ..

rm -rf demotemp
