#!/bin/bash

#Make directory structure for easy upload
mkdir $2$3

#Make tarball and copy it into directory
svn co https://svn.participatoryculture.org/svn/dtv/trunk/resources/
resources/tv/maketarball $2$3
#cp Democracy-$2$3.tar.gz $2$3/src/

# copy the source directory

tar zxvf Democracy-$2$3.tar.gz
mv Democracy-$2$3 democracyplayer-$2$3
cp -a resources/tv/ubuntu-deb-package/debian democracyplayer-$2$3

#build the rpm
cd democracyplayer-$2$3
dpkg-buildpackage -us -uc -rfakeroot
cd ..

mv *.deb $2$3

#copy Directory onto PCF2 user's home directory
echo "Press enter to upload files..."
read i
scp -r $2$3 $1@pcf2.osuosl.org:.

#File Cleanup
echo "Cleaning up files..."
rm -rf Democracy-$2$3.tar.gz
rm -rf resources/
rm -rf democracyplayer-$2$3
rm democracyplayer_$2$3-1ubuntupcf*
