#!/bin/bash

apt-get install debhelper fakeroot cdbs pbuilder lintian

if [ ! -e ./pbuilder/ ]; then
    mkdir ./pbuilder/
fi

if [ ! -f ~/.pbuilderrc ]; then
    echo "Creating .pbuilderrc file...."
    echo "COMPONENTS=\"main restricted universe multiverse\"" > ~/.pbuilderrc;
fi

if [ ${1} ]
then
    if [ -f ./pbuilder/$1-base.tgz ]; then
        echo "Updating $1";
        sudo pbuilder update --distribution $1 --basetgz ./pbuilder/$1-base.tgz;
    else
        echo "Creating $1";
        sudo pbuilder create --distribution $1 \
           --othermirror "deb http://archive.ubuntu.com/ubuntu $1 universe multiverse" \
           --basetgz ./pbuilder/$1-base.tgz;
    fi
else
    echo "Syntax: buildenv <dir>";
fi
