#!/bin/bash

apt-get install debhelper fakeroot cdbs pbuilder lintian

mkdir ./pbuilder/

function create_or_update {
    if [ -f ./pbuilder/$1-base.tgz ]; then
        echo "";
        echo "updating $1";
        sudo pbuilder update --distribution $1 --basetgz ./pbuilder/$1-base.tgz;
    else
        echo "";
        echo "creating $1";
        sudo pbuilder create --distribution $1 \
           --othermirror "deb http://archive.ubuntu.com/ubuntu $1 universe multiverse" \
           --basetgz ./pbuilder/$1-base.tgz;
    fi
}

create_or_update dapper ;
create_or_update feisty ;
create_or_update gutsy ;
create_or_update hardy ;
