#include "nsISupports.idl"

[scriptable, uuid(EAB4645D-7F9C-4db0-90E4-F9A6F3897E2A)]
interface nsIMultiply : nsISupports
{
  /**
   * This interface multiplies the two operands and returns the result.
   */
  long multiply(in long a, in long b); 
};
