/*
 * Miro - an RSS based video player application
 * Copyright (C) 2005-2007 Participatory Culture Foundation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
*/

#include "nsISupports.idl"

interface nsIDOMWindow;

[scriptable, uuid(506247A1-775B-4377-9687-ADD4FEED198A)]
interface pcfIDTVVLCRenderer : nsISupports
{
    void init(in nsIDOMWindow window);
    void reset();
    boolean canPlayURL(in AString url);
    void selectURL(in AString url);
    void play();
    void playFromTime(in float position);
    void pause();
    void pauseForDrag();
    void stop();
    void goToBeginningOfMovie();
    float getCurrentTime();
    float getDuration();
    void setCurrentTime(in float position);
    void setVolume(in float volume);
    void goFullscreen();
    void extractMovieData(in AString url, in AString screenshot_filename);
};
