#include "nsISupports.idl"

interface nsIDOMWindow;

[scriptable, uuid(506247A1-775B-4377-9687-ADD4FEED198A)]
interface pcfIDTVVLCRenderer : nsISupports
{
    void init(in nsIDOMWindow window);
    void reset();
    boolean canPlayURL(in AString url);
    void selectURL(in AString url);
    void play();
    void pause();
    void pauseForDrag();
    void stop();
    void goToBeginningOfMovie();
    float getCurrentTime();
    void setCurrentTime(in float position);
    void setVolume(in float volume);
    void goFullscreen();
};
