#include "nsISupports.idl"

interface nsIDOMWindow;

[scriptable, uuid(7E70142F-ABC9-4d6e-BDB8-EDC747FCD2A3)]
interface pcfIDTVJSBridge : nsISupports
{
  void init(in nsIDOMWindow window);
  void closeWindow();
  void xulNavigateDisplay(in string area, in AString uri);
  void xulAddElementAtEnd(in string area, in AString xml, in AString id);
  void xulAddElementBefore(in string area, in AString xml, in AString id);
  void xulRemoveElement(in string area, in AString id);
  void xulChangeElement(in string area, in AString id, in AString xml);
  void xulHideElement(in string area, in AString id);
  void xulShowElement(in string area, in AString id);
  void copyTextToClipboard(in AString text);
  void showContextMenu(in AString menuItems);
  void showChoiceDialog(in unsigned long id, in AString title, 
        in AString description, in AString defaultLabel, 
        in AString otherLabel);
  void showThreeChoiceDialog(in unsigned long id, in AString title, 
        in AString description, in AString defaultLabel, 
        in AString secondLabel, in AString thirdLabel);
  void showMessageBoxDialog(in unsigned long id, in AString title, 
        in AString description);
  void showHTTPAuthDialog(in unsigned long id, in AString description);
  void showTextEntryDialog(in unsigned long id, in AString title, 
        in AString description, in AString defaultLabel, 
        in AString otherLabel, in AString prefillText);
  void showSearchChannelDialog(in unsigned long id);
  void showBugReportDialog(in AString when, in AString report);
  void showVideoDisplay();
  void hideVideoDisplay();
  void positionVolumeSlider(in float volume);
  void toggleFullscreen();
  void enterFullscreen();
  void leaveFullscreen();
  void setActionGroupEnabled(in AString group, in boolean enabled);
  void updateLabel(in AString id, in AString label);
  void updateVideoFilename(in AString newFilename);
  void saveVideo();
  void setSliderText(in PRInt32 elasped);
  void moveSlider(in float fractionDone);
};
