#include "nsISupports.idl"
#include "nsIDOMDocument.idl"

interface nsICommandLine;

[scriptable, uuid(8ABB2E1D-6624-4457-A4BD-EBFA6156D426)]
interface pcfIDTVPyBridge : nsISupports
{
  /**
   * Called on application startup.
   */
  void onStartup(in nsIDOMDocument mainWindowDocument);
  void onShutdown();
  void handleCommandLine(in nsICommandLine commandLine);
  void handleSecondCommandLine(in nsICommandLine commandLine);
  void pageLoadFinished(in string area);
  void setVolume(in float volume);
  void quit();
  void removeCurrentChannel();
  void updateCurrentChannel();
  void updateChannels();
  void showHelp();
  void copyChannelLink();
};
